### ISSUE TITLE
bastokenizer crashes with trailing newlines

### ISSUE THREAD

**Issue by KrisKennaway** [AppleCommander/bastools#18]
Sample Program:

"""
100 PRINT "HELLO, WORLD!"

"""

This crashes with:

make/bt Test.bas  -o Test.tok
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: picocli.CommandLine$ExecutionException: Error while calling command (io.github.applecommander.bastokenizer.tools.bt.Main@18769467): java.util.NoSuchElementException
	at picocli.CommandLine.execute(CommandLine.java:837)
	at picocli.CommandLine.access$700(CommandLine.java:111)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:994)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:962)
	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:870)
	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1153)
	at picocli.CommandLine.call(CommandLine.java:1405)
	at picocli.CommandLine.call(CommandLine.java:1333)
	at io.github.applecommander.bastokenizer.tools.bt.Main.main(Main.java:102)
	... 8 more
Caused by: java.util.NoSuchElementException
	at java.util.LinkedList.removeFirst(LinkedList.java:270)
	at java.util.LinkedList.remove(LinkedList.java:685)
	at io.github.applecommander.bastokenizer.api.Parser.expectNumber(Parser.java:64)
	at io.github.applecommander.bastokenizer.api.Parser.readLine(Parser.java:34)
	at io.github.applecommander.bastokenizer.api.Parser.parse(Parser.java:27)
	at io.github.applecommander.bastokenizer.tools.bt.Main.process(Main.java:144)
	at io.github.applecommander.bastokenizer.tools.bt.Main.call(Main.java:113)
	at io.github.applecommander.bastokenizer.tools.bt.Main.call(Main.java:32)
	at picocli.CommandLine.execute(CommandLine.java:830)
	... 16 more
make[1]: *** [Test.tok] Error 1
make: *** [all] Error 2
Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by a2geek** [comment]
The parse is less than ideal. `bt` does allow (albeit grudgingly) blank lines, but not if it's the _last_ line. :roll_eyes: 

Alternate sample:

```
$ cat issue18b.bas 

100 PRINT "HELLO, WORLD!"



110 END
```

**Comment by a2geek** [comment]
I just published [`bt` v0.3.0](https://github.com/AppleCommander/bastools/releases/tag/v0.3.0) which should fix this.

**Comment by KrisKennaway** [comment]
Thanks very much!
