### ISSUE TITLE
[bt] Improve error reporting when parsing fails

### ISSUE THREAD

**Issue by KrisKennaway** [AppleCommander/bastools#20]
Currently if you typo something in the input program and tokenization fails, the resulting error message is not very informative about where is the problem.  e.g. you get a nested exception where the lowest level is:

Caused by: java.io.IOException: Unknown! ttype=63, nval=30.000000, sval=null
	at io.github.applecommander.bastokenizer.api.TokenReader.next(TokenReader.java:149)
	at io.github.applecommander.bastokenizer.api.TokenReader.tokenize(TokenReader.java:54)
	at io.github.applecommander.bastokenizer.api.TokenReader.tokenize(TokenReader.java:40)
	at io.github.applecommander.bastokenizer.tools.bt.Main.process(Main.java:139)
	at io.github.applecommander.bastokenizer.tools.bt.Main.call(Main.java:113)
	at io.github.applecommander.bastokenizer.tools.bt.Main.call(Main.java:32)
	at picocli.CommandLine.execute(CommandLine.java:830)

which is trying to tell me that there is an unexpected '?' character (ASCII 63) somewhere on line 30.

**Comment by a2geek** [comment]
Yeah, that's not great.  I do think the `nval` is just whatever number was last converted, unfortunately. 

For instance, using:
```
10 ? "hello"
20 goto 10!
30 rem that should generate an error...
40 stop
```

Yields this wonderful error:
```
$ bt --list issue20.bas 
Error: Unknown! ttype=33, nval=10.000000, sval=null
```

If I move the exclamation in front of the number, I get:
```
$ bt --list issue20.bas 
Error: Unknown! ttype=33, nval=20.000000, sval=null
```

I'll look at tracking the physical line number and the AppleSoft line number.

**Comment by a2geek** [comment]
Displaying the "physical" line number but not the AppleSoft line number as this is occurring in the tokenizer, which doesn't comprehend anything about the program.
